add condition to show dialog
flavor-receitinhas/App-receitinhas pull request #10
Opened 2024-06-07 20:42 UTC by Skynoshine

2024-06-07 22:26 UTC, cledsonv requested changes

2024-06-07 22:26 UTC, cledsonv commented on lib/src/feactures/recipes/presenter/controller/create_recipe_controller.dart
> +        listMultiMedia.isNotEmpty;
Poderia validar com os outros campos aqui tambem para caso o usuario tenha voltado das telas posteriores e apagado o conteudo da primeira tela

2024-06-08 01:25 UTC, cledsonv approved these changes

2024-06-09 21:41 UTC, lucascardo12 commented on lib/src/feactures/recipes/presenter/ui/pages/introduce_create_page.dart
> +                        ? CookieSheetBottom(
Coloca esse bottom sheet em um arquivo separado

2024-06-22 20:17 UTC, merged